LprFeature.exe Bad_(1)_threshold_region.txt in.txt out.txt 0 2
LprFeature.exe Bad_(2)_threshold_region.txt in.txt out.txt 0 2
LprFeature.exe Bad_(3)_threshold_region.txt in.txt out.txt 0 2
LprFeature.exe Bad_(4)_threshold_region.txt in.txt out.txt 0 2
LprFeature.exe Bad_(5)_threshold_region.txt in.txt out.txt 0 2
LprFeature.exe Bad_(6)_threshold_region.txt in.txt out.txt 0 2
LprFeature.exe Bad_(7)_threshold_region.txt in.txt out.txt 0 2
LprFeature.exe Bad_(8)_threshold_region.txt in.txt out.txt 0 2
LprFeature.exe Bad_(9)_threshold_region.txt in.txt out.txt 0 2
LprFeature.exe Bad_(10)_threshold_region.txt in.txt out.txt 0 2
LprFeature.exe Good_(1)_threshold_region.txt in.txt out.txt 1 2
LprFeature.exe Good_(2)_threshold_region.txt in.txt out.txt 1 2
LprFeature.exe Good_(3)_threshold_region.txt in.txt out.txt 1 2
LprFeature.exe Good_(4)_threshold_region.txt in.txt out.txt 1 2
LprFeature.exe Good_(5)_threshold_region.txt in.txt out.txt 1 2
LprFeature.exe Good_(6)_threshold_region.txt in.txt out.txt 1 2